backend:
  name: git-gateway
  repo: MAXBERENGAUT/maxberengaut.com
  branch: main # Branch to update (optional; defaults to master)

# These lines should *not* be indented
# publish_mode: editorial_workflow

media_folder: "/content" # Media files will be stored in the repo under static/images/uploads
public_folder: "/content" # The src attribute for uploaded media will begin with /images/uploads

site_url: https://maxberengaut.com
display_url: https://maxberengaut.com
# logo_url: # url to logo image to be displayed on admin site

collections:
  - name: "Photos" # Used in routes, e.g., /admin/collections/blog
    editor:
      preview: false # removed preview due to bug with setting image as identifier
    extension: json
    format: json
    label: "Photography" # Used in the UI
    folder: "content/photos" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    identifier_field: image
    fields:
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Title", name: "title", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Date", name: "date", widget: "string", required: false}
      - {label: "Location", name: "location", widget: "string", required: false}